### ISSUE TITLE
Make extension truly standalone

### ISSUE THREAD

**Issue by peterkraume** [spoonerWeb/t3cs_sessions#1]
There are references to svg files from the main template in two files:
- `Resources/Private/Templates/Session/ListPast.html`
- `Resources/Private/Templates/Session/List.html`

```
<use xlink:href="/typo3conf/ext/t3cs/Resources/Public/Images/icons.svg#tag" />
<use xlink:href="/typo3conf/ext/t3cs/Resources/Public/Images/icons.svg#star" />
```

**Comment by spoonerWeb** [comment]
Fixed in commit 3d1d3fc1d7e664a28871b6f4a1785a1a1cc35a0e
